name: whatsapp_bot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  provider: ^6.1.1
  table_calendar: ^3.0.9
  font_awesome_flutter: ^10.5.0
  # SQLite paketleri (Android AGP 8+ ile uyumlu güncel sürümler)
  sqflite: ^2.3.3+1
  path: ^1.9.0
  # Background service ve HTTP paketleri
  workmanager: ^0.5.2
  http: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/python_scripts/